// Mocks generated by Mockito 5.4.4 from annotations
// in groceryapp/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i15;

import 'package:dartz/dartz.dart' as _i2;
import 'package:groceryapp/core/failure/failure.dart' as _i7;
import 'package:groceryapp/core/usecase/usecase.dart' as _i10;
import 'package:groceryapp/features/data/datasources/grocery_remote_data_source.dart'
    as _i9;
import 'package:groceryapp/features/data/model/grocery_model.dart' as _i3;
import 'package:groceryapp/features/domain/entities/grocery_entity.dart' as _i8;
import 'package:groceryapp/features/domain/repositories/grocery_repository.dart'
    as _i4;
import 'package:groceryapp/features/domain/usecases/get_groceries_usecase.dart'
    as _i11;
import 'package:groceryapp/features/domain/usecases/get_grocry_by_id_usecase.dart'
    as _i12;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroceryModel_1 extends _i1.SmartFake implements _i3.GroceryModel {
  _FakeGroceryModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroceryRepository_2 extends _i1.SmartFake
    implements _i4.GroceryRepository {
  _FakeGroceryRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroceryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroceryRepository extends _i1.Mock implements _i4.GroceryRepository {
  MockGroceryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Grocery>>> getGroceries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroceries,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.Grocery>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.Grocery>>(
          this,
          Invocation.method(
            #getGroceries,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Grocery>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.Grocery>> getGrocery(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGrocery,
          [id],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.Grocery>>.value(
            _FakeEither_0<_i7.Failure, _i8.Grocery>(
          this,
          Invocation.method(
            #getGrocery,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.Grocery>>);
}

/// A class which mocks [GroceryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroceryRemoteDataSource extends _i1.Mock
    implements _i9.GroceryRemoteDataSource {
  MockGroceryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.GroceryModel>> getGroceries() => (super.noSuchMethod(
        Invocation.method(
          #getGroceries,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.GroceryModel>>.value(<_i3.GroceryModel>[]),
      ) as _i6.Future<List<_i3.GroceryModel>>);

  @override
  _i6.Future<_i3.GroceryModel> getGroceryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroceryById,
          [id],
        ),
        returnValue: _i6.Future<_i3.GroceryModel>.value(_FakeGroceryModel_1(
          this,
          Invocation.method(
            #getGroceryById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.GroceryModel>);
}

/// A class which mocks [Usecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsecase<Type, params> extends _i1.Mock
    implements _i10.Usecase<Type, params> {
  MockUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, Type>> call(params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, Type>>.value(
            _FakeEither_0<_i7.Failure, Type>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, Type>>);
}

/// A class which mocks [GetGroceriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGroceriesUseCase extends _i1.Mock
    implements _i11.GetGroceriesUseCase {
  MockGetGroceriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GroceryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroceryRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.GroceryRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Grocery>>> call(
          _i10.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.Grocery>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.Grocery>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Grocery>>>);
}

/// A class which mocks [GetGroceryByIdUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGroceryByIdUsecase extends _i1.Mock
    implements _i12.GetGroceryByIdUsecase {
  MockGetGroceryByIdUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GroceryRepository get groceryRepository => (super.noSuchMethod(
        Invocation.getter(#groceryRepository),
        returnValue: _FakeGroceryRepository_2(
          this,
          Invocation.getter(#groceryRepository),
        ),
      ) as _i4.GroceryRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.Grocery>> call(
          _i12.GetParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.Grocery>>.value(
            _FakeEither_0<_i7.Failure, _i8.Grocery>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.Grocery>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i5.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i5.Response>);

  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i15.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
      ) as _i6.Future<_i15.Uint8List>);

  @override
  _i6.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
